# Data Overview (From PostgreSQL):

In [ ]:
# db_table_data_overview.py

# Import necessary libraries for data overview
from sqlalchemy import create_engine, inspect
import pandas as pd

# --------------------------------------------
# DATABASE CONNECTION
# --------------------------------------------
DB_URI = "postgresql+psycopg2://postgres:Sansen27%40@127.0.0.1:5432/attendance_db"
engine = create_engine(DB_URI)
inspector = inspect(engine)

# --------------------------------------------
# LIST TABLES
# --------------------------------------------
tables = inspector.get_table_names()
print("\n=== TABLES IN DATABASE ===")
for t in tables:
    print("-", t)
print("\n")

# --------------------------------------------
# DISPLAY TABLE DETAILS AND DATA
# --------------------------------------------
for table_name in tables:
    print(f"=== TABLE: {table_name} ===")

    # Column details
    columns = inspector.get_columns(table_name)
    print("Attributes (Columns):")
    for col in columns:
        print(f"  - {col['name']} | {col['type']} | nullable: {col['nullable']}")
    print()

    # Fetch and display all rows
    df = pd.read_sql_table(table_name, con=engine)
    print("All Rows:")
    if df.empty:
        print("  (No rows found)")
    else:
        print(df.to_string(index=False))

    # Show shape of the data
    print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")
    print("=" * 90 + "\n")

=== TABLES IN DATABASE ===
- sessions
- courses
- sections
- terms
- enrollments
- class_sessions
- attendance_records
- users
- auth_credentials


=== TABLE: sessions ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - user_id | INTEGER | nullable: False
  - session_token | VARCHAR(64) | nullable: False
  - created_at | TIMESTAMP | nullable: True
  - expires_at | TIMESTAMP | nullable: False
  - ip | VARCHAR(64) | nullable: True
  - user_agent | VARCHAR(255) | nullable: True
  - revoked_at | TIMESTAMP | nullable: True

All Rows:
 id  user_id                    session_token                 created_at                 expires_at        ip                                                                                                            user_agent                 revoked_at
 10        1 212cc0eb048241d7a4ab58d40d38a740 2025-10-19 17:34:07.477986 2025-10-26 21:34:07.477455 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 21:35:47.777335
 11        1 fff4f38c36fd48ddb3525600e9d72de4 2025-10-19 17:35:47.780018 2025-10-26 21:35:47.779744 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 21:48:41.873792
 12        1 36ba981bcbf247c29861f91962ac7961 2025-10-19 17:48:41.886546 2025-10-26 21:48:41.886000 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 22:10:18.301877
 13        1 90979d4de5ea4a2ab108d7c34a11718c 2025-10-19 18:10:18.317151 2025-10-26 22:10:18.316528 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 22:14:08.558084
 14        1 117ce66e77ae4b3c830743117442edb9 2025-10-19 18:14:08.573009 2025-10-26 22:14:08.572721 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 22:16:50.472205
 15        1 978ae9d401cb4ba0a6defb70ebd5a856 2025-10-19 18:16:50.486907 2025-10-26 22:16:50.486226 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 22:19:28.473070
 16        1 1d27edc21d494611bced1f99a74d070f 2025-10-19 18:19:28.485032 2025-10-26 22:19:28.484460 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 22:26:49.508689
 17        1 db74d58c75304e85b6f81b361120c15d 2025-10-19 18:26:49.522550 2025-10-26 22:26:49.521938 127.0.0.1                                                                                                            curl/8.7.1 2025-10-19 22:43:04.391077
 18        1 61ff31bef0804cf4afe20b8b813cd1ba 2025-10-19 18:43:04.416495 2025-10-26 22:43:04.415679 127.0.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 2025-10-19 22:46:17.259310
 19        1 51476a7e3fe84ad69ac5c21cab57d160 2025-10-19 18:46:17.275477 2025-10-26 22:46:17.275217 127.0.0.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36                        NaT

Shape: 10 rows × 8 columns
==========================================================================================

=== TABLE: courses ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - code | VARCHAR(20) | nullable: False
  - title | VARCHAR(120) | nullable: False

All Rows:
  id  code                         title
   1 CS101                   Intro to CS
   2 CS102               Data Structures
   5 CS102               Data Structures
  10 CS201   Machine Learning Principles
  20 CS301   Natural Language Processing
 101 CS401   Natural Language Processing
 102 CS402         Large Language Models
 103 CS403               Computer Vision
 104 CS404        Reinforcement Learning
 105 CS405                   Data Mining
 403 CS410      Applied Machine Learning
 905 CS501 Machine Learning Fundamentals
 906 CS502       Advanced Data Analytics
 954 CS601          Deep Learning Basics
 955 CS602   Data Visualization Advanced
1004 CS701                     AI Ethics
1005 CS702        Reinforcement Learning

Shape: 17 rows × 3 columns
==========================================================================================

=== TABLE: sections ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - course_id | INTEGER | nullable: True
  - term_id | INTEGER | nullable: True
  - instructor_id | INTEGER | nullable: True
  - meeting_days | VARCHAR(20) | nullable: True
  - start_time | TIME | nullable: True
  - end_time | TIME | nullable: True
  - room | VARCHAR(50) | nullable: True

All Rows:
  id  course_id  term_id  instructor_id meeting_days start_time end_time     room
   1          1        1              2          MWF   09:00:00 10:00:00 Room 101
   2          2        2              4           TR   11:00:00 12:30:00 Room 202
   5          5        5              6           TR   11:00:00 12:30:00 Room 202
  10         10       10              9           MW   14:00:00 15:30:00 Room 303
  20         20       20             31           MW   10:00:00 11:30:00 Room 505
  21         20       20             32           TR   13:00:00 14:30:00 Room 506
 101        101      101            111           MW   09:00:00 10:30:00 Room 101
 102        102      101            112           TR   11:00:00 12:30:00 Room 102
 103        103      101            113           MW   13:00:00 14:30:00 Room 103
 104        104      102            114           TR   09:00:00 10:30:00 Room 104
 105        105      102            115           MW   11:00:00 12:30:00 Room 105
 301        103      101            311           MW   10:00:00 11:30:00 Room 201
 302        104      101            312           TR   12:00:00 13:30:00 Room 202
 303        105      102            313           MW   14:00:00 15:30:00 Room 203
 405        403      404            401           MW   09:00:00 10:30:00 Room 303
 909        905      907            901          MWF   09:00:00 10:30:00 Room 101
 910        906      908            902           TR   11:00:00 12:30:00 Room 202
 958        954      956            951          MWF   10:00:00 11:30:00 Room 301
 959        955      957            952           TR   13:00:00 14:30:00 Room 402
1008       1004     1006           1001          MWF   09:00:00 10:30:00 Room 501
1009       1005     1007           1002           TR   14:00:00 15:30:00 Room 602

Shape: 21 rows × 8 columns
==========================================================================================

=== TABLE: terms ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - name | VARCHAR(50) | nullable: False
  - start_date | DATE | nullable: True
  - end_date | DATE | nullable: True

All Rows:
  id        name start_date   end_date
   1   Fall 2025 2025-09-01 2025-12-20
   2 Spring 2026 2026-01-15 2026-05-10
   5 Spring 2026 2026-01-15 2026-05-10
  10   Fall 2026 2026-08-25 2026-12-15
  20   Fall 2026 2026-08-25 2026-12-15
 101   Fall 2026 2026-08-25 2026-12-15
 102 Spring 2027 2027-01-15 2027-05-10
 404   Fall 2028 2028-08-20 2028-12-10
 907 Spring 2030 2030-01-10 2030-05-05
 908 Summer 2030 2030-06-01 2030-08-15
 956   Fall 2030 2030-08-20 2030-12-15
 957 Spring 2031 2031-01-15 2031-05-10
1006   Fall 2031 2031-08-25 2031-12-12
1007 Spring 2032 2032-01-10 2032-05-05

Shape: 14 rows × 4 columns
==========================================================================================

=== TABLE: enrollments ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - section_id | INTEGER | nullable: True
  - student_id | INTEGER | nullable: True

All Rows:
  id  section_id  student_id
   1           1           1
   2           2           3
   5           5           5
  10          10           5
  21          20          21
  22          20          22
  23          20          23
  24          20          24
  25          20          25
  26          20          26
  27          21          27
  28          21          28
  29          21          29
  30          21          30
  31          21          21
  32          21          23
 101         101         101
 102         101         102
 103         101         103
 104         102         104
 105         102         105
 106         102         101
 107         103         106
 108         103         107
 109         103         102
 110         104         108
 111         104         109
 112         104         110
 113         105         101
 114         105         104
 115         105         105
 301         301         301
 302         301         302
 303         301         303
 304         301         304
 305         302         305
 306         302         306
 307         302         307
 308         302         302
 309         303         308
 310         303         309
 311         303         310
 312         303         301
 406         405         402
 911         909         903
 912         909         904
 913         910         903
 914         910         904
 960         958         953
 961         959         953
1010        1008        1003
1011        1009        1003

Shape: 52 rows × 3 columns
==========================================================================================

=== TABLE: class_sessions ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - section_id | INTEGER | nullable: True
  - session_date | DATE | nullable: False
  - status | VARCHAR(20) | nullable: False

All Rows:
  id  section_id session_date    status
   1           1   2025-10-20 scheduled
   2           2   2026-02-05 scheduled
   3           2   2026-02-12 scheduled
   5           5   2026-02-05 scheduled
   6           5   2026-02-12 scheduled
  10          10   2026-09-02 scheduled
  11          10   2026-09-09 scheduled
  20          20   2026-09-03 scheduled
  21          20   2026-09-10 scheduled
  22          20   2026-09-17 scheduled
  23          20   2026-09-24 scheduled
  24          21   2026-09-04 scheduled
  25          21   2026-09-11 scheduled
  26          21   2026-09-18 scheduled
  27          21   2026-09-25 scheduled
 101         101   2026-09-01 scheduled
 102         101   2026-09-08 scheduled
 103         102   2026-09-02 scheduled
 104         102   2026-09-09 scheduled
 105         103   2026-09-03 scheduled
 106         103   2026-09-10 scheduled
 107         104   2027-01-20 scheduled
 108         104   2027-01-27 scheduled
 109         105   2027-01-21 scheduled
 110         105   2027-01-28 scheduled
 301         301   2026-09-05 scheduled
 302         301   2026-09-12 scheduled
 303         302   2026-09-06 scheduled
 304         302   2026-09-13 scheduled
 305         303   2027-01-21 scheduled
 306         303   2027-01-28 scheduled
 407         405   2028-09-05 scheduled
 408         405   2028-09-12 scheduled
 915         909   2030-01-15 scheduled
 916         909   2030-01-22 scheduled
 917         910   2030-06-03 scheduled
 918         910   2030-06-10 scheduled
 962         958   2030-08-25 scheduled
 963         958   2030-09-01 scheduled
 964         959   2031-01-20 scheduled
 965         959   2031-01-27 scheduled
1012        1008   2031-08-30 scheduled
1013        1008   2031-09-06 scheduled
1014        1009   2032-01-15 scheduled
1015        1009   2032-01-22 scheduled

Shape: 45 rows × 4 columns
==========================================================================================

=== TABLE: attendance_records ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - session_id | INTEGER | nullable: True
  - student_id | INTEGER | nullable: True
  - status | VARCHAR(20) | nullable: False
  - marked_at | TIMESTAMP | nullable: True
  - notes | TEXT | nullable: True

All Rows:
  id  session_id  student_id  status                  marked_at notes
   1           1           1 present 2025-10-19 15:46:48.259805  None
   2           2           3 present 2025-10-20 02:09:18.296667  None
   3           3           3  absent 2025-10-20 02:09:18.296667  None
   5           5           5 present 2025-10-20 14:41:42.548085  None
   6           6           5  absent 2025-10-20 14:41:42.548085  None
  10          10           5 present 2025-10-20 15:16:07.825795  None
  11          11           5  absent 2025-10-20 15:16:07.825795  None
  20          20          21 present 2025-10-20 18:14:54.731658  None
  21          21          21  absent 2025-10-20 18:14:54.731658  None
  22          22          21 present 2025-10-20 18:14:54.731658  None
  23          23          21 present 2025-10-20 18:14:54.731658  None
  24          20          22 present 2025-10-20 18:14:54.731658  None
  25          21          22 present 2025-10-20 18:14:54.731658  None
  26          22          22  absent 2025-10-20 18:14:54.731658  None
  27          23          22 present 2025-10-20 18:14:54.731658  None
  28          20          23  absent 2025-10-20 18:14:54.731658  None
  29          21          23 present 2025-10-20 18:14:54.731658  None
  30          22          23 present 2025-10-20 18:14:54.731658  None
  31          23          23  absent 2025-10-20 18:14:54.731658  None
  32          20          24 present 2025-10-20 18:14:54.731658  None
  33          21          24 present 2025-10-20 18:14:54.731658  None
  34          22          24 present 2025-10-20 18:14:54.731658  None
  35          23          24  absent 2025-10-20 18:14:54.731658  None
  36          20          25  absent 2025-10-20 18:14:54.731658  None
  37          21          25 present 2025-10-20 18:14:54.731658  None
  38          22          25 present 2025-10-20 18:14:54.731658  None
  39          23          25 present 2025-10-20 18:14:54.731658  None
  40          20          26 present 2025-10-20 18:14:54.731658  None
  41          21          26 present 2025-10-20 18:14:54.731658  None
  42          22          26  absent 2025-10-20 18:14:54.731658  None
  43          23          26 present 2025-10-20 18:14:54.731658  None
  44          24          27 present 2025-10-20 18:14:54.731658  None
  45          25          27  absent 2025-10-20 18:14:54.731658  None
  46          26          27 present 2025-10-20 18:14:54.731658  None
  47          27          27 present 2025-10-20 18:14:54.731658  None
  48          24          28  absent 2025-10-20 18:14:54.731658  None
  49          25          28 present 2025-10-20 18:14:54.731658  None
  50          26          28 present 2025-10-20 18:14:54.731658  None
  51          27          28  absent 2025-10-20 18:14:54.731658  None
  52          24          29 present 2025-10-20 18:14:54.731658  None
  53          25          29 present 2025-10-20 18:14:54.731658  None
  54          26          29 present 2025-10-20 18:14:54.731658  None
  55          27          29 present 2025-10-20 18:14:54.731658  None
  56          24          30  absent 2025-10-20 18:14:54.731658  None
  57          25          30 present 2025-10-20 18:14:54.731658  None
  58          26          30  absent 2025-10-20 18:14:54.731658  None
  59          27          30 present 2025-10-20 18:14:54.731658  None
  60          24          21 present 2025-10-20 18:14:54.731658  None
  61          25          21  absent 2025-10-20 18:14:54.731658  None
  62          26          21 present 2025-10-20 18:14:54.731658  None
  63          27          21 present 2025-10-20 18:14:54.731658  None
  64          24          23 present 2025-10-20 18:14:54.731658  None
  65          25          23  absent 2025-10-20 18:14:54.731658  None
  66          26          23 present 2025-10-20 18:14:54.731658  None
  67          27          23 present 2025-10-20 18:14:54.731658  None
 101         101         101 present 2025-10-20 18:29:05.324692  None
 102         101         102  absent 2025-10-20 18:29:05.324692  None
 103         101         103 present 2025-10-20 18:29:05.324692  None
 104         102         101 present 2025-10-20 18:29:05.324692  None
 105         102         102 present 2025-10-20 18:29:05.324692  None
 106         102         103  absent 2025-10-20 18:29:05.324692  None
 107         103         104 present 2025-10-20 18:29:05.324692  None
 108         103         105 present 2025-10-20 18:29:05.324692  None
 109         103         101  absent 2025-10-20 18:29:05.324692  None
 110         104         104 present 2025-10-20 18:29:05.324692  None
 111         104         105  absent 2025-10-20 18:29:05.324692  None
 112         104         101 present 2025-10-20 18:29:05.324692  None
 113         105         101 present 2025-10-20 18:29:05.324692  None
 114         105         104 present 2025-10-20 18:29:05.324692  None
 115         105         105 present 2025-10-20 18:29:05.324692  None
 301         301         301 present 2025-10-20 18:48:59.393514  None
 302         301         302  absent 2025-10-20 18:48:59.393514  None
 303         301         303 present 2025-10-20 18:48:59.393514  None
 304         301         304 present 2025-10-20 18:48:59.393514  None
 305         302         301 present 2025-10-20 18:48:59.393514  None
 306         302         302 present 2025-10-20 18:48:59.393514  None
 307         302         303  absent 2025-10-20 18:48:59.393514  None
 308         302         304 present 2025-10-20 18:48:59.393514  None
 309         303         308 present 2025-10-20 18:48:59.393514  None
 310         303         309 present 2025-10-20 18:48:59.393514  None
 311         303         310  absent 2025-10-20 18:48:59.393514  None
 312         303         301 present 2025-10-20 18:48:59.393514  None
 409         407         402 present 2025-10-20 23:28:21.551627  None
 410         408         402  absent 2025-10-20 23:28:21.551627  None
 919         915         903 present 2025-10-24 18:31:59.839255  None
 920         916         903  absent 2025-10-24 18:31:59.839255  None
 921         915         904 present 2025-10-24 18:31:59.839255  None
 922         916         904 present 2025-10-24 18:31:59.839255  None
 923         917         903 present 2025-10-24 18:31:59.839255  None
 924         918         903 present 2025-10-24 18:31:59.839255  None
 925         917         904  absent 2025-10-24 18:31:59.839255  None
 926         918         904 present 2025-10-24 18:31:59.839255  None
 966         962         953 present 2025-10-24 18:40:13.320190  None
 967         963         953  absent 2025-10-24 18:40:13.320190  None
 968         964         953 present 2025-10-24 18:40:13.320190  None
 969         965         953 present 2025-10-24 18:40:13.320190  None
1016        1012        1003 present 2025-10-24 18:48:14.079792  None
1017        1013        1003  absent 2025-10-24 18:48:14.079792  None
1018        1014        1003 present 2025-10-24 18:48:14.079792  None
1019        1015        1003 present 2025-10-24 18:48:14.079792  None

Shape: 100 rows × 6 columns
==========================================================================================

=== TABLE: users ===
Attributes (Columns):
  - id | INTEGER | nullable: False
  - name | VARCHAR(100) | nullable: True
  - username | VARCHAR(100) | nullable: True
  - role | VARCHAR(20) | nullable: True

All Rows:
  id                 name username    role
 101          Mia Student  mia1234 student
 102       Oliver Student  oli2345 student
 103       Harper Student  har3456 student
 104       Elijah Student  eli4567 student
 105        Avery Student  ave5678 student
 106        James Student  jam6789 student
 107       Amelia Student  ame7890 student
 108     Benjamin Student  ben8901 student
 109       Evelyn Student  eve9012 student
 110        Lucas Student  luc0123 student
 111 Charlotte Instructor  cha1122 teacher